name: Pull Request Check

on: push

jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: instrumenta/kubeval-action@master
      with:
        files: deployment.yaml
  slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: yes-i-still-love-you
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Kubeval test!'
        SLACK_TITLE: Attention
        SLACK_USERNAME: kubeval
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
